<Project Sdk="Aspire.AppHost.Sdk/13.4.6">

  <ItemGroup>
    <ProjectReference Include="..\TsiBroker.ApiService\TsiBroker.ApiService.csproj" />
    <ProjectReference Include="..\TsiBroker.Im.Api\TsiBroker.Im.Api.csproj" />
    <ProjectReference Include="..\TsiBroker.Ru.Api\TsiBroker.Ru.Api.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.JavaScript" Version="13.4.6" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>20a4e41a-f4b0-4694-9ef3-f2f69f5a9569</UserSecretsId>
  </PropertyGroup>

</Project>
